version: '{branch}.{build}'
clone_depth: 20
only_commits:
  files:
    - .appveyor.yml
    - contrib/appveyor.ps1
    - setup.py
    - trac/**/*.py
    - trac/**/*.js
    - trac/**/*.html
    - tracopt/**/*.py
    - tracopt/**/*.js
    - tracopt/**/*.html
init:
- ps: >-
    # Note 1: in 'Environment variables' groups above, use:

    #  - SKIP_ENV=1 to completely skip a problematic environment

    #  - SKIP_BUILD=1 to skip the Build step

    #  - SKIP_TESTS=1 to skip the Tests step

    # Note 2: restoration of cached directories happens *after* this step
environment:
  matrix:
  - PYTHONHOME: C:\Python38
    TRAC_TEST_DB_URI:
  - PYTHONHOME: C:\Python37-x64
    TRAC_TEST_DB_URI:
  - PYTHONHOME: C:\Python36-x64
    TRAC_TEST_DB_URI:
  - PYTHONHOME: C:\Python35-x64
    TRAC_TEST_DB_URI:
  - PYTHONHOME: C:\Python38-x64
    TRAC_TEST_DB_URI: sqlite:test.db
  - PYTHONHOME: C:\Miniconda37
    TRAC_TEST_DB_URI: mysql://tracuser:password@localhost/trac?charset=utf8mb4
  - PYTHONHOME: C:\Miniconda37-x64
    TRAC_TEST_DB_URI: postgres://tracuser:password@localhost/trac?schema=tractest
services:
- mysql
- postgresql93
install:
- ps: >-
    . .\contrib\appveyor.ps1

    Trac-Install
cache: C:\projects\dependencies
build_script:
- ps: >-
    . .\contrib\appveyor.ps1

    Trac-Build
test_script:
- ps: >-
    . .\contrib\appveyor.ps1

    Trac-Tests
artifacts:
- path: 'dist\*'
